# Generated by Django 4.2.11 on 2024-04-08 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_choice_question_delete_mymodel_choice_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
