# Generated by Django 4.2.11 on 2024-04-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_delete_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='response_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
