# Generated by Django 4.2.11 on 2024-04-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='response_text',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
